export const DATA = {
  adaptiveScreenSize: [
    { name: 'sm', remSize: '30rem', pxSize: '480px' },
    { name: 'md', remSize: '48rem', pxSize: '768px' },
    { name: 'lg', remSize: '61rem', pxSize: '976px' },
    { name: 'xl', remSize: '90rem', pxSize: '1440px' },
  ],
  paddingMargin: [
    { value: '0', remSize: '0rem', pxSize: '0px' },
    { value: '0.5', remSize: '0.125rem', pxSize: '2px' },
    { value: '1', remSize: '0.25rem', pxSize: '4px' },
    { value: '1.5', remSize: '0.375rem', pxSize: '6px' },
    { value: '2', remSize: '0.5rem', pxSize: '8px' },
    { value: '2.5', remSize: '0.625rem', pxSize: '10px' },
    { value: '3', remSize: '0.75rem', pxSize: '12px' },
    { value: '3.5', remSize: '0.875rem', pxSize: '14px' },
    { value: '4', remSize: '1rem', pxSize: '16px' },
    { value: '5', remSize: '1.25rem', pxSize: '20px' },
    { value: '6', remSize: '1.5rem', pxSize: '24px' },
    { value: '7', remSize: '1.75rem', pxSize: '28px' },
    { value: '8', remSize: '2rem', pxSize: '32px' },
    { value: '9', remSize: '2.25rem', pxSize: '36px' },
    { value: '10', remSize: '2.5rem', pxSize: '40px' },
    { value: '11', remSize: '2.75rem', pxSize: '44px' },
    { value: '12', remSize: '3rem', pxSize: '48px' },
    { value: '14', remSize: '3.5rem', pxSize: '56px' },
    { value: '16', remSize: '4rem', pxSize: '64px' },
    { value: '20', remSize: '5rem', pxSize: '80px' },
    { value: '24', remSize: '6rem', pxSize: '96px' },
    { value: '28', remSize: '7rem', pxSize: '112px' },
    { value: '32', remSize: '8rem', pxSize: '128px' },
    { value: '36', remSize: '9rem', pxSize: '144px' },
    { value: '40', remSize: '10rem', pxSize: '160px' },
    { value: '44', remSize: '11rem', pxSize: '176px' },
    { value: '48', remSize: '12rem', pxSize: '192px' },
    { value: '52', remSize: '13rem', pxSize: '208px' },
    { value: '56', remSize: '14rem', pxSize: '224px' },
    { value: '60', remSize: '15rem', pxSize: '240px' },
    { value: '64', remSize: '16rem', pxSize: '256px' },
    { value: '72', remSize: '18rem', pxSize: '288px' },
    { value: '80', remSize: '20rem', pxSize: '320px' },
    { value: '96', remSize: '24rem', pxSize: '384px' },
  ],
  maxWidth: [
    { name: 'max-w-0', remSize: '0rem', pxSize: '0px' },
    { name: 'max-w-none', remSize: 'none', pxSize: 'none' },
    { name: 'max-w-xs', remSize: '20rem', pxSize: '320px' },
    { name: 'max-w-sm', remSize: '24rem', pxSize: '384px' },
    { name: 'max-w-md', remSize: '28rem', pxSize: '448px' },
    { name: 'max-w-lg', remSize: '32rem', pxSize: '512px' },
    { name: 'max-w-xl', remSize: '36rem', pxSize: '576px' },
    { name: 'max-w-2xl', remSize: '42rem', pxSize: '672px' },
    { name: 'max-w-3xl', remSize: '48rem', pxSize: '768px' },
    { name: 'max-w-4xl', remSize: '56rem', pxSize: '896px' },
    { name: 'max-w-5xl', remSize: '64rem', pxSize: '1024px' },
    { name: 'max-w-6xl', remSize: '72rem', pxSize: '1152px' },
    { name: 'max-w-7xl', remSize: '80rem', pxSize: '1280px' },
    { name: 'max-w-full', remSize: '100%', pxSize: '100%' }
  ],
}