import React, { ReactElement } from "react";
import * as Icons from "../../../../components/Icon";
import { IconProps, IconMapItem } from "./types";

export const getIconsMap = (props: IconProps = {}): IconMapItem[] => ([
  { 
    title: 'Arrow',
    iconsList: [
      { name: 'AltArrowDownIcon', component: <Icons.AltArrowDownIcon {...props} /> },
      { name: 'AltArrowLeftIcon', component: <Icons.AltArrowLeftIcon {...props} /> },
      { name: 'AltArrowRightIcon', component: <Icons.AltArrowRightIcon {...props} /> },
      { name: 'AltArrowUpIcon', component: <Icons.AltArrowUpIcon {...props} /> },
      { name: 'ArrowDownIcon', component: <Icons.ArrowDownIcon {...props} /> },
      { name: 'ArrowLeftDownIcon', component: <Icons.ArrowLeftDownIcon {...props} /> },
      { name: 'ArrowLeftIcon', component: <Icons.ArrowLeftIcon {...props} /> },
      { name: 'ArrowLeftUpIcon', component: <Icons.ArrowLeftUpIcon {...props} /> },
      { name: 'ArrowRightDownIcon', component: <Icons.ArrowRightDownIcon {...props} /> },
      { name: 'ArrowRightIcon', component: <Icons.ArrowRightIcon {...props} /> },
      { name: 'ArrowRightUpIcon', component: <Icons.ArrowRightUpIcon {...props} /> },
      { name: 'ArrowUpIcon', component: <Icons.ArrowUpIcon {...props} /> },
      { name: 'DoubleAltArrowDownIcon', component: <Icons.DoubleAltArrowDownIcon {...props} /> },
      { name: 'DoubleAltArrowLeftIcon', component: <Icons.DoubleAltArrowLeftIcon {...props} /> },
      { name: 'DoubleAltArrowRightIcon', component: <Icons.DoubleAltArrowRightIcon {...props} /> },
      { name: 'DoubleAltArrowUpIcon', component: <Icons.DoubleAltArrowUpIcon {...props} /> },
      { name: 'RestartCircleIcon', component: <Icons.RestartCircleIcon {...props} /> },
      { name: 'RestartIcon', component: <Icons.RestartIcon {...props} /> },
      { name: 'RestartSquareIcon', component: <Icons.RestartSquareIcon {...props} /> },
      { name: 'RoundAltArrowDownIcon', component: <Icons.RoundAltArrowDownIcon {...props} /> },
      { name: 'RoundAltArrowLeftIcon', component: <Icons.RoundAltArrowLeftIcon {...props} /> },
      { name: 'RoundAltArrowRightIcon', component: <Icons.RoundAltArrowRightIcon {...props} /> },
      { name: 'RoundAltArrowUpIcon', component: <Icons.RoundAltArrowUpIcon {...props} /> },
      { name: 'RoundArrowDownIcon', component: <Icons.RoundArrowDownIcon {...props} /> },
      { name: 'RoundArrowLeftDownIcon', component: <Icons.RoundArrowLeftDownIcon {...props} /> },
      { name: 'RoundArrowLeftIcon', component: <Icons.RoundArrowLeftIcon {...props} /> },
      { name: 'RoundArrowLeftUpIcon', component: <Icons.RoundArrowLeftUpIcon {...props} /> },
      { name: 'RoundArrowRightDownIcon', component: <Icons.RoundArrowRightDownIcon {...props} /> },
      { name: 'RoundArrowRightIcon', component: <Icons.RoundArrowRightIcon {...props} /> },
      { name: 'RoundArrowRightUpIcon', component: <Icons.RoundArrowRightUpIcon {...props} /> },
      { name: 'RoundArrowUpIcon', component: <Icons.RoundArrowUpIcon {...props} /> },
      { name: 'RoundDoubleAltArrowDownIcon', component: <Icons.RoundDoubleAltArrowDownIcon {...props} /> },
      { name: 'RoundDoubleAltArrowLeftIcon', component: <Icons.RoundDoubleAltArrowLeftIcon {...props} /> },
      { name: 'RoundDoubleAltArrowRightIcon', component: <Icons.RoundDoubleAltArrowRightIcon {...props} /> },
      { name: 'RoundDoubleAltArrowUpIcon', component: <Icons.RoundDoubleAltArrowUpIcon {...props} /> },
      { name: 'RoundSortHorizontalIcon', component: <Icons.RoundSortHorizontalIcon {...props} /> },
      { name: 'RoundSortVerticalIcon', component: <Icons.RoundSortVerticalIcon {...props} /> },
      { name: 'RoundTransferDiagonalIcon', component: <Icons.RoundTransferDiagonalIcon {...props} /> },
      { name: 'RoundTransferHorizontalIcon', component: <Icons.RoundTransferHorizontalIcon {...props} /> },
      { name: 'RoundTransferVerticalIcon', component: <Icons.RoundTransferVerticalIcon {...props} /> },
      { name: 'SortHorizontalIcon', component: <Icons.SortHorizontalIcon {...props} /> },
      { name: 'SortVerticalIcon', component: <Icons.SortVerticalIcon {...props} /> },
      { name: 'SquareAltArrowDownIcon', component: <Icons.SquareAltArrowDownIcon {...props} /> },
      { name: 'SquareAltArrowLeftIcon', component: <Icons.SquareAltArrowLeftIcon {...props} /> },
      { name: 'SquareAltArrowRightIcon', component: <Icons.SquareAltArrowRightIcon {...props} /> },
      { name: 'SquareAltArrowUpIcon', component: <Icons.SquareAltArrowUpIcon {...props} /> },
      { name: 'SquareArrowDownIcon', component: <Icons.SquareArrowDownIcon {...props} /> },
      { name: 'SquareArrowLeftDownIcon', component: <Icons.SquareArrowLeftDownIcon {...props} /> },
      { name: 'SquareArrowLeftIcon', component: <Icons.SquareArrowLeftIcon {...props} /> },
      { name: 'SquareArrowLeftUpIcon', component: <Icons.SquareArrowLeftUpIcon {...props} /> },
      { name: 'SquareArrowRightDownIcon', component: <Icons.SquareArrowRightDownIcon {...props} /> },
      { name: 'SquareArrowRightIcon', component: <Icons.SquareArrowRightIcon {...props} /> },
      { name: 'SquareArrowRightUpIcon', component: <Icons.SquareArrowRightUpIcon {...props} /> },
      { name: 'SquareArrowUpIcon', component: <Icons.SquareArrowUpIcon {...props} /> },
      { name: 'SquareDoubleAltArrowDownIcon', component: <Icons.SquareDoubleAltArrowDownIcon {...props} /> },
      { name: 'SquareDoubleAltArrowLeftIcon', component: <Icons.SquareDoubleAltArrowLeftIcon {...props} /> },
      { name: 'SquareDoubleAltArrowRightIcon', component: <Icons.SquareDoubleAltArrowRightIcon {...props} /> },
      { name: 'SquareDoubleAltArrowUpIcon', component: <Icons.SquareDoubleAltArrowUpIcon {...props} /> },
      { name: 'SquareSortHorizontalIcon', component: <Icons.SquareSortHorizontalIcon {...props} /> },
      { name: 'SquareSortVerticalIcon', component: <Icons.SquareSortVerticalIcon {...props} /> },
      { name: 'SquareTransferHorizontalIcon', component: <Icons.SquareTransferHorizontalIcon {...props} /> },
      { name: 'SquareTransferVerticalIcon', component: <Icons.SquareTransferVerticalIcon {...props} /> },
      { name: 'TransferHorizontalIcon', component: <Icons.TransferHorizontalIcon {...props} /> },
      { name: 'TransferVerticalIcon', component: <Icons.TransferVerticalIcon {...props} /> },
    ]
  }, {
    title: "Arrow Action",
    iconsList: [
      { name: 'ArrowToDownLeftIcon', component: <Icons.ArrowToDownLeftIcon {...props} /> },
      { name: 'ArrowToDownRightIcon', component: <Icons.ArrowToDownRightIcon {...props} /> },
      { name: 'ArrowToTopLeftIcon', component: <Icons.ArrowToTopLeftIcon {...props} /> },
      { name: 'ArrowToTopRightIcon', component: <Icons.ArrowToTopRightIcon {...props} /> },
      { name: 'CircleBottomDownIcon', component: <Icons.CircleBottomDownIcon {...props} /> },
      { name: 'CircleBottomUpIcon', component: <Icons.CircleBottomUpIcon {...props} /> },
      { name: 'CircleTopDownIcon', component: <Icons.CircleTopDownIcon {...props} /> },
      { name: 'CircleTopUpIcon', component: <Icons.CircleTopUpIcon {...props} /> },
      { name: 'DownloadMinimalisticIcon', component: <Icons.DownloadMinimalisticIcon {...props} /> },
      { name: 'DownloadSquareIcon', component: <Icons.DownloadSquareIcon {...props} /> },
      { name: 'DownloadTwiceSquareIcon', component: <Icons.DownloadTwiceSquareIcon {...props} /> },
      { name: 'DownloadIcon', component: <Icons.DownloadIcon {...props} /> },
      { name: 'ExitIcon', component: <Icons.ExitIcon {...props} /> },
      { name: 'ExportIcon', component: <Icons.ExportIcon {...props} /> },
      { name: 'ForwardArrowIcon', component: <Icons.ForwardArrowIcon {...props} /> },
      { name: 'ForwardV2Icon', component: <Icons.ForwardV2Icon {...props} /> },
      { name: 'ImportIcon', component: <Icons.ImportIcon {...props} /> },
      { name: 'LoginV2Icon', component: <Icons.LoginV2Icon {...props} /> },
      { name: 'LoginV3Icon', component: <Icons.LoginV3Icon {...props} /> },
      { name: 'LoginIcon', component: <Icons.LoginIcon {...props} /> },
      { name: 'LogoutV2Icon', component: <Icons.LogoutV2Icon {...props} /> },
      { name: 'LogoutV3Icon', component: <Icons.LogoutV3Icon {...props} /> },
      { name: 'LogoutIcon', component: <Icons.LogoutIcon {...props} /> },
      { name: 'MaximizeSquareV2Icon', component: <Icons.MaximizeSquareV2Icon {...props} /> },
      { name: 'MaximizeSquareV3Icon', component: <Icons.MaximizeSquareV3Icon {...props} /> },
      { name: 'MaximizeSquareMinimalisticIcon', component: <Icons.MaximizeSquareMinimalisticIcon {...props} /> },
      { name: 'MaximizeSquareIcon', component: <Icons.MaximizeSquareIcon {...props} /> },
      { name: 'MaximizeIcon', component: <Icons.MaximizeIcon {...props} /> },
      { name: 'MinimizeSquareV2Icon', component: <Icons.MinimizeSquareV2Icon {...props} /> },
      { name: 'MinimizeSquareV3Icon', component: <Icons.MinimizeSquareV3Icon {...props} /> },
      { name: 'MinimizeSquareMinimalisticIcon', component: <Icons.MinimizeSquareMinimalisticIcon {...props} /> },
      { name: 'MinimizeSquareIcon', component: <Icons.MinimizeSquareIcon {...props} /> },
      { name: 'MinimizeIcon', component: <Icons.MinimizeIcon {...props} /> },
      { name: 'ReciveSquareIcon', component: <Icons.ReciveSquareIcon {...props} /> },
      { name: 'ReciveTwiceSquareIcon', component: <Icons.ReciveTwiceSquareIcon {...props} /> },
      { name: 'ReorderArrowIcon', component: <Icons.ReorderArrowIcon {...props} /> },
      { name: 'ReplyV2Icon', component: <Icons.ReplyV2Icon {...props} /> },
      { name: 'ReplyIcon', component: <Icons.ReplyIcon {...props} /> },
      { name: 'ScaleIcon', component: <Icons.ScaleIcon {...props} /> },
      { name: 'ScreenShareIcon', component: <Icons.ScreenShareIcon {...props} /> },
      { name: 'SendSquareIcon', component: <Icons.SendSquareIcon {...props} /> },
      { name: 'SendTwiceSquareIcon', component: <Icons.SendTwiceSquareIcon {...props} /> },
      { name: 'SquareBottomDownIcon', component: <Icons.SquareBottomDownIcon {...props} /> },
      { name: 'SquareBottomUpIcon', component: <Icons.SquareBottomUpIcon {...props} /> },
      { name: 'SquareTopDownIcon', component: <Icons.SquareTopDownIcon {...props} /> },
      { name: 'SquareTopUpIcon', component: <Icons.SquareTopUpIcon {...props} /> },
      { name: 'UndoLeftRoundSquareIcon', component: <Icons.UndoLeftRoundSquareIcon {...props} /> },
      { name: 'UndoLeftRoundIcon', component: <Icons.UndoLeftRoundIcon {...props} /> },
      { name: 'UndoLeftSquareIcon', component: <Icons.UndoLeftSquareIcon {...props} /> },
      { name: 'UndoLeftIcon', component: <Icons.UndoLeftIcon {...props} /> },
      { name: 'UndoRightRoundSquareIcon', component: <Icons.UndoRightRoundSquareIcon {...props} /> },
      { name: 'UndoRightRoundIcon', component: <Icons.UndoRightRoundIcon {...props} /> },
      { name: 'UndoRightSquareIcon', component: <Icons.UndoRightSquareIcon {...props} /> },
      { name: 'UndoRightIcon', component: <Icons.UndoRightIcon {...props} /> },
      { name: 'UploadMinimalisticIcon', component: <Icons.UploadMinimalisticIcon {...props} /> },
      { name: 'UploadSquareIcon', component: <Icons.UploadSquareIcon {...props} /> },
      { name: 'UploadTwiceSquareIcon', component: <Icons.UploadTwiceSquareIcon {...props} /> },
      { name: 'UploadIcon', component: <Icons.UploadIcon {...props} /> },
    ]
  },
  {
    title: "Business & Statistic",
    iconsList: [
      { name: 'ChartV2Icon', component: <Icons.ChartV2Icon {...props} /> },
      { name: 'ChartIcon', component: <Icons.ChartIcon {...props} /> },
      { name: 'ChartSquareIcon', component: <Icons.ChartSquareIcon {...props} /> },
      { name: 'ChartSquareV2Icon', component: <Icons.ChartSquareV2Icon {...props} /> },
      { name: 'CourseDownIcon', component: <Icons.CourseDownIcon {...props} /> },
      { name: 'CourseUpIcon', component: <Icons.CourseUpIcon {...props} /> },
      { name: 'DiagramDownIcon', component: <Icons.DiagramDownIcon {...props} /> },
      { name: 'DiagramUpIcon', component: <Icons.DiagramUpIcon {...props} /> },
      { name: 'GraphDownIcon', component: <Icons.GraphDownIcon {...props} /> },
      { name: 'GraphUpIcon', component: <Icons.GraphUpIcon {...props} /> },
      { name: 'GraphIcon', component: <Icons.GraphIcon {...props} /> },
      { name: 'PieChartV2Icon', component: <Icons.PieChartV2Icon {...props} /> },
      { name: 'PieChartV3Icon', component: <Icons.PieChartV3Icon {...props} /> },
      { name: 'PieChartIcon', component: <Icons.PieChartIcon {...props} /> },
      { name: 'PresentationGraphIcon', component: <Icons.PresentationGraphIcon {...props} /> },
      { name: 'RoundGraphIcon', component: <Icons.RoundGraphIcon {...props} /> },
    ]
  },
  {
    title: "Design Tools",
    iconsList: [
      { name: 'AlignBottomIcon', component: <Icons.AlignBottomIcon {...props} /> },
      { name: 'AlignHorizontalSpacingIcon', component: <Icons.AlignHorizontalSpacingIcon {...props} /> },
      { name: 'AlignHorizontalCenterIcon', component: <Icons.AlignHorizontalCenterIcon {...props} /> },
      { name: 'AlignLeftIcon', component: <Icons.AlignLeftIcon {...props} /> },
      { name: 'AlignRightIcon', component: <Icons.AlignRightIcon {...props} /> },
      { name: 'AlignTopIcon', component: <Icons.AlignTopIcon {...props} /> },
      { name: 'AlignVerticalCenterIcon', component: <Icons.AlignVerticalCenterIcon {...props} /> },
      { name: 'AlignVerticalSpacingIcon', component: <Icons.AlignVerticalSpacingIcon {...props} /> },
      { name: 'ColourTuneingIcon', component: <Icons.ColourTuneingIcon {...props} /> },
      { name: 'CropIcon', component: <Icons.CropIcon {...props} /> },
      { name: 'FlipHorizontalIcon', component: <Icons.FlipHorizontalIcon {...props} /> },
      { name: 'FlipVerticalIcon', component: <Icons.FlipVerticalIcon {...props} /> },
      { name: 'LayersIcon', component: <Icons.LayersIcon {...props} /> },
      { name: 'MirrorLeftIcon', component: <Icons.MirrorLeftIcon {...props} /> },
      { name: 'MirrorRightIcon', component: <Icons.MirrorRightIcon {...props} /> },
      { name: 'RadialBlurIcon', component: <Icons.RadialBlurIcon {...props} /> },
      { name: 'RulerAngularIcon', component: <Icons.RulerAngularIcon {...props} /> },
      { name: 'RulerPenIcon', component: <Icons.RulerPenIcon {...props} /> },
      { name: 'RulerIcon', component: <Icons.RulerIcon {...props} /> },
      { name: 'ThreeSquaresIcon', component: <Icons.ThreeSquaresIcon {...props} /> },
    ]
  },
  {
    title: "EssentionalUI",
    iconsList: [
      { name: 'AddCircleIcon', component: <Icons.AddCircleIcon {...props} /> },
      { name: 'AddSquareIcon', component: <Icons.AddSquareIcon {...props} /> },
      { name: 'BoltCircleIcon', component: <Icons.BoltCircleIcon {...props} /> },
      { name: 'BoltIcon', component: <Icons.BoltIcon {...props} /> },
      { name: 'BoxMinimalisticIcon', component: <Icons.BoxMinimalisticIcon {...props} /> },
      { name: 'BoxIcon', component: <Icons.BoxIcon {...props} /> },
      { name: 'CheckCircleIcon', component: <Icons.CheckCircleIcon {...props} /> },
      { name: 'CheckSquareIcon', component: <Icons.CheckSquareIcon {...props} /> },
      { name: 'CloseCircleIcon', component: <Icons.CloseCircleIcon {...props} /> },
      { name: 'CloseSquareIcon', component: <Icons.CloseSquareIcon {...props} /> },
      { name: 'CopyIcon', component: <Icons.CopyIcon {...props} /> },
      { name: 'CrownMinimalisticIcon', component: <Icons.CrownMinimalisticIcon {...props} /> },
      { name: 'CrownStarIcon', component: <Icons.CrownStarIcon {...props} /> },
      { name: 'CursorIcon', component: <Icons.CursorIcon {...props} /> },
      { name: 'DatabaseIcon', component: <Icons.DatabaseIcon {...props} /> },
      { name: 'FeedIcon', component: <Icons.FeedIcon {...props} /> },
      { name: 'FlagV2Icon', component: <Icons.FlagV2Icon {...props} /> },
      { name: 'FlagIcon', component: <Icons.FlagIcon {...props} /> },
      { name: 'ForbiddenCircleIcon', component: <Icons.ForbiddenCircleIcon {...props} /> },
      { name: 'ForbiddenIcon', component: <Icons.ForbiddenIcon {...props} /> },
      { name: 'GiftIcon', component: <Icons.GiftIcon {...props} /> },
      { name: 'HamburgerMenuIcon', component: <Icons.HamburgerMenuIcon {...props} /> },
      { name: 'HomeV2Icon', component: <Icons.HomeV2Icon {...props} /> },
      { name: 'HomeAddIcon', component: <Icons.HomeAddIcon {...props} /> },
      { name: 'HomeSmileIcon', component: <Icons.HomeSmileIcon {...props} /> },
      { name: 'HomeIcon', component: <Icons.HomeIcon {...props} /> },
      { name: 'MagnetIcon', component: <Icons.MagnetIcon {...props} /> },
      { name: 'MentionSquareIcon', component: <Icons.MentionSquareIcon {...props} /> },
      { name: 'MinusCircleIcon', component: <Icons.MinusCircleIcon {...props} /> },
      { name: 'MinusSquareIcon', component: <Icons.MinusSquareIcon {...props} /> },
      { name: 'PaperBinIcon', component: <Icons.PaperBinIcon {...props} /> },
      { name: 'PinListIcon', component: <Icons.PinListIcon {...props} /> },
      { name: 'PlateIcon', component: <Icons.PlateIcon {...props} /> },
      { name: 'PostsCarouselHorizontalIcon', component: <Icons.PostsCarouselHorizontalIcon {...props} /> },
      { name: 'PostsCarouselVerticalIcon', component: <Icons.PostsCarouselVerticalIcon {...props} /> },
      { name: 'PowerIcon', component: <Icons.PowerIcon {...props} /> },
      { name: 'ReorderIcon', component: <Icons.ReorderIcon {...props} /> },
      { name: 'ShareCircleIcon', component: <Icons.ShareCircleIcon {...props} /> },
      { name: 'SliderHorizontalIcon', component: <Icons.SliderHorizontalIcon {...props} /> },
      { name: 'SliderMinimalisticHorizontalIcon', component: <Icons.SliderMinimalisticHorizontalIcon {...props} /> },
      { name: 'SliderVerticalMinimalisticIcon', component: <Icons.SliderVerticalMinimalisticIcon {...props} /> },
      { name: 'SliderVerticalIcon', component: <Icons.SliderVerticalIcon {...props} /> },
      { name: 'SortIcon', component: <Icons.SortIcon {...props} /> },
      { name: 'SubtitlesIcon', component: <Icons.SubtitlesIcon {...props} /> },
      { name: 'TargetIcon', component: <Icons.TargetIcon {...props} /> },
      { name: 'TrafficEconomyIcon', component: <Icons.TrafficEconomyIcon {...props} /> },
      { name: 'TrafficIcon', component: <Icons.TrafficIcon {...props} /> },
      { name: 'TrashBinV2Icon', component: <Icons.TrashBinV2Icon {...props} /> },
      { name: 'TrashBinMinimalisticV2Icon', component: <Icons.TrashBinMinimalisticV2Icon {...props} /> },
      { name: 'TrashBinMinimalisticIcon', component: <Icons.TrashBinMinimalisticIcon {...props} /> },
      { name: 'TrashBinTrashIcon', component: <Icons.TrashBinTrashIcon {...props} /> },
    ]
  },
  {
    title: "List",
    iconsList: [
      { name: 'BillIcon', component: <Icons.BillIcon {...props} /> },
      { name: 'ChecklistMinimalisticIcon', component: <Icons.ChecklistMinimalisticIcon {...props} /> },
      { name: 'ChecklistIcon', component: <Icons.ChecklistIcon {...props} /> },
      { name: 'ListArrowDownMinimalisticIcon', component: <Icons.ListArrowDownMinimalisticIcon {...props} /> },
      { name: 'ListArrowDownIcon', component: <Icons.ListArrowDownIcon {...props} /> },
      { name: 'ListArrowUpMinimalisticIcon', component: <Icons.ListArrowUpMinimalisticIcon {...props} /> },
      { name: 'ListArrowUpIcon', component: <Icons.ListArrowUpIcon {...props} /> },
      { name: 'ListCheckMinimalisticIcon', component: <Icons.ListCheckMinimalisticIcon {...props} /> },
      { name: 'ListCheckIcon', component: <Icons.ListCheckIcon {...props} /> },
      { name: 'ListCrossMinimalisticIcon', component: <Icons.ListCrossMinimalisticIcon {...props} /> },
      { name: 'ListCrossIcon', component: <Icons.ListCrossIcon {...props} /> },
      { name: 'ListDownMinimalisticIcon', component: <Icons.ListDownMinimalisticIcon {...props} /> },
      { name: 'ListDownIcon', component: <Icons.ListDownIcon {...props} /> },
      { name: 'ListUpMinimalisticIcon', component: <Icons.ListUpMinimalisticIcon {...props} /> },
      { name: 'ListUpIcon', component: <Icons.ListUpIcon {...props} /> },
      { name: 'ListV1Icon', component: <Icons.ListV1Icon {...props} /> },
      { name: 'ListIcon', component: <Icons.ListIcon {...props} /> },
      { name: 'PlaylistMinimalisticIcon', component: <Icons.PlaylistMinimalisticIcon {...props} /> },
      { name: 'PlaylistV2Icon', component: <Icons.PlaylistV2Icon {...props} /> },
      { name: 'PlaylistMinimalistic3Icon', component: <Icons.PlaylistMinimalistic3Icon {...props} /> },
      { name: 'PlaylistIcon', component: <Icons.PlaylistIcon {...props} /> },
      { name: 'SortFromBottomToTopIcon', component: <Icons.SortFromBottomToTopIcon {...props} /> },
      { name: 'SortFromTopToBottomIcon', component: <Icons.SortFromTopToBottomIcon {...props} /> },
    ]
  },
  {
    title: "Messages & Conversation",
    iconsList: [
      { name: 'ForwardIcon', component: <Icons.ForwardIcon {...props} /> },
      { name: 'InboxArchiveIcon', component: <Icons.InboxArchiveIcon {...props} /> },
      { name: 'InboxInIcon', component: <Icons.InboxInIcon {...props} /> },
      { name: 'InboxOutIcon', component: <Icons.InboxOutIcon {...props} /> },
      { name: 'InboxIcon', component: <Icons.InboxIcon {...props} /> },
      { name: 'LetterOpenedIcon', component: <Icons.LetterOpenedIcon {...props} /> },
      { name: 'LetterIcon', component: <Icons.LetterIcon {...props} /> },
      { name: 'MultipleForwardLeftIcon', component: <Icons.MultipleForwardLeftIcon {...props} /> },
      { name: 'MultipleForwardRightIcon', component: <Icons.MultipleForwardRightIcon {...props} /> },
      { name: 'PaperclipV2Icon', component: <Icons.PaperclipV2Icon {...props} /> },
      { name: 'PaperclipRoundedV2Icon', component: <Icons.PaperclipRoundedV2Icon {...props} /> },
      { name: 'PaperclipRoundedIcon', component: <Icons.PaperclipRoundedIcon {...props} /> },
      { name: 'PaperclipIcon', component: <Icons.PaperclipIcon {...props} /> },
      { name: 'PenV2Icon', component: <Icons.PenV2Icon {...props} /> },
      { name: 'PenNewSquareIcon', component: <Icons.PenNewSquareIcon {...props} /> },
      { name: 'PenIcon', component: <Icons.PenIcon {...props} /> },
      { name: 'PlainV2Icon', component: <Icons.PlainV2Icon {...props} /> },
      { name: 'PlainV3Icon', component: <Icons.PlainV3Icon {...props} /> },
      { name: 'SquareForwardIcon', component: <Icons.SquareForwardIcon {...props} /> },
      { name: 'SquareShareLineIcon', component: <Icons.SquareShareLineIcon {...props} /> },
      { name: 'UnreadIcon', component: <Icons.UnreadIcon {...props} /> },
    ]
  },
  {
    title: "Money",
    iconsList: [
      { name: 'BanknoteV2Icon', component: <Icons.BanknoteV2Icon {...props} /> },
      { name: 'BanknoteIcon', component: <Icons.BanknoteIcon {...props} /> },
      { name: 'BillCrossIcon', component: <Icons.BillCrossIcon {...props} /> },
      { name: 'BillCheckIcon', component: <Icons.BillCheckIcon {...props} /> },
      { name: 'BillListIcon', component: <Icons.BillListIcon {...props} /> },
      { name: 'MoneyBillIcon', component: <Icons.MoneyBillIcon {...props} /> },
      { name: 'CardV2Icon', component: <Icons.CardV2Icon {...props} /> },
      { name: 'CardReciveIcon', component: <Icons.CardReciveIcon {...props} /> },
      { name: 'CardSendIcon', component: <Icons.CardSendIcon {...props} /> },
      { name: 'CardTransferIcon', component: <Icons.CardTransferIcon {...props} /> },
      { name: 'CardIcon', component: <Icons.CardIcon {...props} /> },
      { name: 'CardholderIcon', component: <Icons.CardholderIcon {...props} /> },
      { name: 'DollarMinimalisticIcon', component: <Icons.DollarMinimalisticIcon {...props} /> },
      { name: 'DollarIcon', component: <Icons.DollarIcon {...props} /> },
      { name: 'MoneyBagIcon', component: <Icons.MoneyBagIcon {...props} /> },
      { name: 'SafeCircleIcon', component: <Icons.SafeCircleIcon {...props} /> },
      { name: 'SafeSquareIcon', component: <Icons.SafeSquareIcon {...props} /> },
      { name: 'TagHorizontalIcon', component: <Icons.TagHorizontalIcon {...props} /> },
      { name: 'TagPriceIcon', component: <Icons.TagPriceIcon {...props} /> },
      { name: 'TagIcon', component: <Icons.TagIcon {...props} /> },
      { name: 'TickerStarIcon', component: <Icons.TickerStarIcon {...props} /> },
      { name: 'VerifiedCheckIcon', component: <Icons.VerifiedCheckIcon {...props} /> },
      { name: 'WadOfMoneyIcon', component: <Icons.WadOfMoneyIcon {...props} /> },
      { name: 'WalletV2Icon', component: <Icons.WalletV2Icon {...props} /> },
      { name: 'WalletMoneyIcon', component: <Icons.WalletMoneyIcon {...props} /> },
      { name: 'WalletIcon', component: <Icons.WalletIcon {...props} /> },
    ]
  },
  {
    title: "Notes",
    iconsList: [
      { name: 'ArchiveCheckIcon', component: <Icons.ArchiveCheckIcon {...props} /> },
      { name: 'ArchiveDownMinimlisticIcon', component: <Icons.ArchiveDownMinimlisticIcon {...props} /> },
      { name: 'ArchiveDownIcon', component: <Icons.ArchiveDownIcon {...props} /> },
      { name: 'ArchiveMinimalisticIcon', component: <Icons.ArchiveMinimalisticIcon {...props} /> },
      { name: 'ArchiveUpMinimlisticIcon', component: <Icons.ArchiveUpMinimlisticIcon {...props} /> },
      { name: 'ArchiveUpIcon', component: <Icons.ArchiveUpIcon {...props} /> },
      { name: 'ArchiveIcon', component: <Icons.ArchiveIcon {...props} /> },
      { name: 'ClipboardAddIcon', component: <Icons.ClipboardAddIcon {...props} /> },
      { name: 'ClipboardCheckIcon', component: <Icons.ClipboardCheckIcon {...props} /> },
      { name: 'ClipboardListIcon', component: <Icons.ClipboardListIcon {...props} /> },
      { name: 'ClipboardRemoveIcon', component: <Icons.ClipboardRemoveIcon {...props} /> },
      { name: 'ClipboardTextIcon', component: <Icons.ClipboardTextIcon {...props} /> },
      { name: 'ClipboardIcon', component: <Icons.ClipboardIcon {...props} /> },
      { name: 'DocumentMedicineIcon', component: <Icons.DocumentMedicineIcon {...props} /> },
      { name: 'DocumentTextIcon', component: <Icons.DocumentTextIcon {...props} /> },
      { name: 'DocumentIcon', component: <Icons.DocumentIcon {...props} /> },
      { name: 'DocumentsMinimalisticIcon', component: <Icons.DocumentsMinimalisticIcon {...props} /> },
      { name: 'DocumentsIcon', component: <Icons.DocumentsIcon {...props} /> },
      { name: 'NotebookIcon', component: <Icons.NotebookIcon {...props} /> },
      { name: 'NotesMinimalisticIcon', component: <Icons.NotesMinimalisticIcon {...props} /> },
      { name: 'NotesIcon', component: <Icons.NotesIcon {...props} /> },
    ]
  },
  {
    title: "Notifications",
    iconsList: [
      { name: 'BellBingIcon', component: <Icons.BellBingIcon {...props} /> },
      { name: 'BellOffIcon', component: <Icons.BellOffIcon {...props} /> },
      { name: 'BellIcon', component: <Icons.BellIcon {...props} /> },
      { name: 'NotificationLinesRemoveIcon', component: <Icons.NotificationLinesRemoveIcon {...props} /> },
      { name: 'NotificationRemoveIcon', component: <Icons.NotificationRemoveIcon {...props} /> },
    ]
  },
  {
    title: "Search",
    iconsList: [
      { name: 'MagniferBugIcon', component: <Icons.MagniferBugIcon {...props} /> },
      { name: 'MagniferZoomInIcon', component: <Icons.MagniferZoomInIcon {...props} /> },
      { name: 'MagniferZoomOutIcon', component: <Icons.MagniferZoomOutIcon {...props} /> },
      { name: 'MagniferIcon', component: <Icons.MagniferIcon {...props} /> },
      { name: 'MinimalisticMagniferBugIcon', component: <Icons.MinimalisticMagniferBugIcon {...props} /> },
      { name: 'MinimalisticMagniferZoomInIcon', component: <Icons.MinimalisticMagniferZoomInIcon {...props} /> },
      { name: 'MinimalisticMagniferZoomOutIcon', component: <Icons.MinimalisticMagniferZoomOutIcon {...props} /> },
      { name: 'MinimalisticMagniferIcon', component: <Icons.MinimalisticMagniferIcon {...props} /> },
    ]
  },
  {
    title: "Security",
    iconsList: [
      { name: 'CodeScanIcon', component: <Icons.CodeScanIcon {...props} /> },
      { name: 'EyeIcon', component: <Icons.EyeIcon {...props} /> },
      { name: 'IncognitoIcon', component: <Icons.IncognitoIcon {...props} /> },
      { name: 'KeyMinimalisticSquareV3Icon', component: <Icons.KeyMinimalisticSquareV3Icon {...props} /> },
      { name: 'KeySquareV2Icon', component: <Icons.KeySquareV2Icon {...props} /> },
      { name: 'KeySquareIcon', component: <Icons.KeySquareIcon {...props} /> },
      { name: 'KeyIcon', component: <Icons.KeyIcon {...props} /> },
      { name: 'LockKeyholeMinimalisticUnlockedIcon', component: <Icons.LockKeyholeMinimalisticUnlockedIcon {...props} /> },
      { name: 'LockKeyholeMinimalisticIcon', component: <Icons.LockKeyholeMinimalisticIcon {...props} /> },
      { name: 'LockUnlockedIcon', component: <Icons.LockUnlockedIcon {...props} /> },
      { name: 'LockIcon', component: <Icons.LockIcon {...props} /> },
      { name: 'PasswordIcon', component: <Icons.PasswordIcon {...props} /> },
      { name: 'ScannerV2Icon', component: <Icons.ScannerV2Icon {...props} /> },
      { name: 'ScannerIcon', component: <Icons.ScannerIcon {...props} /> },
      { name: 'ShieldCheckIcon', component: <Icons.ShieldCheckIcon {...props} /> },
      { name: 'ShieldCrossIcon', component: <Icons.ShieldCrossIcon {...props} /> },
      { name: 'ShieldKeyholeMinimalisticIcon', component: <Icons.ShieldKeyholeMinimalisticIcon {...props} /> },
      { name: 'ShieldKeyholeIcon', component: <Icons.ShieldKeyholeIcon {...props} /> },
      { name: 'ShieldMinimalisticIcon', component: <Icons.ShieldMinimalisticIcon {...props} /> },
      { name: 'ShieldMinusIcon', component: <Icons.ShieldMinusIcon {...props} /> },
      { name: 'ShieldNetworkIcon', component: <Icons.ShieldNetworkIcon {...props} /> },
      { name: 'ShieldPlusIcon', component: <Icons.ShieldPlusIcon {...props} /> },
      { name: 'ShieldStarIcon', component: <Icons.ShieldStarIcon {...props} /> },
      { name: 'ShieldUpIcon', component: <Icons.ShieldUpIcon {...props} /> },
      { name: 'ShieldIcon', component: <Icons.ShieldIcon {...props} /> },
      { name: 'SirenRoundedIcon', component: <Icons.SirenRoundedIcon {...props} /> },
      { name: 'SirenIcon', component: <Icons.SirenIcon {...props} /> },
    ]
  },
  {
    title: "Settings Fine Tuning",
    iconsList: [
      { name: 'TuningV2Icon', component: <Icons.TuningV2Icon {...props} /> },
      { name: 'TuningV4Icon', component: <Icons.TuningV4Icon {...props} /> },
      { name: 'TuningIcon', component: <Icons.TuningIcon {...props} /> },
      { name: 'WidgetV2Icon', component: <Icons.WidgetV2Icon {...props} /> },
      { name: 'WidgetV3Icon', component: <Icons.WidgetV3Icon {...props} /> },
      { name: 'WidgetV4Icon', component: <Icons.WidgetV4Icon {...props} /> },
      { name: 'WidgetV5Icon', component: <Icons.WidgetV5Icon {...props} /> },
      { name: 'WidgetV6Icon', component: <Icons.WidgetV6Icon {...props} /> },
      { name: 'WidgetAddIcon', component: <Icons.WidgetAddIcon {...props} /> },
      { name: 'WidgetIcon', component: <Icons.WidgetIcon {...props} /> },
    ]
  },
  {
    title: "Time",
    iconsList: [
      { name: 'AlarmAddIcon', component: <Icons.AlarmAddIcon {...props} /> },
      { name: 'AlarmPauseIcon', component: <Icons.AlarmPauseIcon {...props} /> },
      { name: 'AlarmPlayIcon', component: <Icons.AlarmPlayIcon {...props} /> },
      { name: 'AlarmRemoveIcon', component: <Icons.AlarmRemoveIcon {...props} /> },
      { name: 'AlarmSleepIcon', component: <Icons.AlarmSleepIcon {...props} /> },
      { name: 'AlarmTurnOffIcon', component: <Icons.AlarmTurnOffIcon {...props} /> },
      { name: 'AlarmIcon', component: <Icons.AlarmIcon {...props} /> },
      { name: 'CalendarAddIcon', component: <Icons.CalendarAddIcon {...props} /> },
      { name: 'CalendarDateIcon', component: <Icons.CalendarDateIcon {...props} /> },
      { name: 'ClockCircleIcon', component: <Icons.ClockCircleIcon {...props} /> },
      { name: 'ClockSquareIcon', component: <Icons.ClockSquareIcon {...props} /> },
      { name: 'HistoryV2Icon', component: <Icons.HistoryV2Icon {...props} /> },
      { name: 'HistoryV3Icon', component: <Icons.HistoryV3Icon {...props} /> },
      { name: 'HourglassLineIcon', component: <Icons.HourglassLineIcon {...props} /> },
      { name: 'HourglassIcon', component: <Icons.HourglassIcon {...props} /> },
      { name: 'StopwatchPauseIcon', component: <Icons.StopwatchPauseIcon {...props} /> },
      { name: 'StopwatchPlayIcon', component: <Icons.StopwatchPlayIcon {...props} /> },
      { name: 'StopwatchIcon', component: <Icons.StopwatchIcon {...props} /> },
      { name: 'WatchRoundIcon', component: <Icons.WatchRoundIcon {...props} /> },
      { name: 'WatchSquareMinimalisticChargeIcon', component: <Icons.WatchSquareMinimalisticChargeIcon {...props} /> },
      { name: 'WatchSquareMinimalisticIcon', component: <Icons.WatchSquareMinimalisticIcon {...props} /> },
      { name: 'WatchSquareIcon', component: <Icons.WatchSquareIcon {...props} /> },
    ]
  },
  {
    title: "Video & Audio Sound",
    iconsList: [
      { name: 'CameraAddIcon', component: <Icons.CameraAddIcon {...props} /> },
      { name: 'CameraRotateIcon', component: <Icons.CameraRotateIcon {...props} /> },
      { name: 'ClapperboardOpenPlayIcon', component: <Icons.ClapperboardOpenPlayIcon {...props} /> },
      { name: 'ClapperboardOpenIcon', component: <Icons.ClapperboardOpenIcon {...props} /> },
      { name: 'ClapperboardTextIcon', component: <Icons.ClapperboardTextIcon {...props} /> },
      { name: 'ClapperboardIcon', component: <Icons.ClapperboardIcon {...props} /> },
      { name: 'FullScreenCircleIcon', component: <Icons.FullScreenCircleIcon {...props} /> },
      { name: 'FullScreenSquareIcon', component: <Icons.FullScreenSquareIcon {...props} /> },
      { name: 'FullScreenIcon', component: <Icons.FullScreenIcon {...props} /> },
      { name: 'GalleryAddIcon', component: <Icons.GalleryAddIcon {...props} /> },
      { name: 'GalleryCheckIcon', component: <Icons.GalleryCheckIcon {...props} /> },
      { name: 'GalleryDownloadIcon', component: <Icons.GalleryDownloadIcon {...props} /> },
      { name: 'GalleryEditIcon', component: <Icons.GalleryEditIcon {...props} /> },
      { name: 'GalleryRemoveIcon', component: <Icons.GalleryRemoveIcon {...props} /> },
      { name: 'GallerySendIcon', component: <Icons.GallerySendIcon {...props} /> },
      { name: 'LibraryIcon', component: <Icons.LibraryIcon {...props} /> },
      { name: 'MusicNoteSliderV2Icon', component: <Icons.MusicNoteSliderV2Icon {...props} /> },
      { name: 'MutedIcon', component: <Icons.MutedIcon {...props} /> },
      { name: 'PauseIcon', component: <Icons.PauseIcon {...props} /> },
      { name: 'PanoramaIcon', component: <Icons.PanoramaIcon {...props} /> },
      { name: 'PipV2Icon', component: <Icons.PipV2Icon {...props} /> },
      { name: 'PipIcon', component: <Icons.PipIcon {...props} /> },
      { name: 'PlayIcon', component: <Icons.PlayIcon {...props} /> },
      { name: 'PlaybackSpeedIcon', component: <Icons.PlaybackSpeedIcon {...props} /> },
      { name: 'QuitPipIcon', component: <Icons.QuitPipIcon {...props} /> },
      { name: 'RecordIcon', component: <Icons.RecordIcon {...props} /> },
      { name: 'ReelIcon', component: <Icons.ReelIcon {...props} /> },
      { name: 'RewindBackIcon', component: <Icons.RewindBackIcon {...props} /> },
      { name: 'RewindForwardIcon', component: <Icons.RewindForwardIcon {...props} /> },
      { name: 'SkipNextIcon', component: <Icons.SkipNextIcon {...props} /> },
      { name: 'SkipPreviousIcon', component: <Icons.SkipPreviousIcon {...props} /> },
      { name: 'SoundwaveSquareIcon', component: <Icons.SoundwaveSquareIcon {...props} /> },
      { name: 'StopIcon', component: <Icons.StopIcon {...props} /> },
      { name: 'StreamIcon', component: <Icons.StreamIcon {...props} /> },
      { name: 'ToPipIcon', component: <Icons.ToPipIcon {...props} /> },
      { name: 'VideoFramePlayHorizontalIcon', component: <Icons.VideoFramePlayHorizontalIcon {...props} /> },
      { name: 'VideoLibraryIcon', component: <Icons.VideoLibraryIcon {...props} /> },
      { name: 'VideocameraAddIcon', component: <Icons.VideocameraAddIcon {...props} /> },
      { name: 'VideocameraRecordIcon', component: <Icons.VideocameraRecordIcon {...props} /> },
      { name: 'VideocameraIcon', component: <Icons.VideocameraIcon {...props} /> },
      { name: 'VolumeCrossIcon', component: <Icons.VolumeCrossIcon {...props} /> },
      { name: 'VolumeLoudIcon', component: <Icons.VolumeLoudIcon {...props} /> },
      { name: 'VolumeSmallIcon', component: <Icons.VolumeSmallIcon {...props} /> },
      { name: 'VolumeIcon', component: <Icons.VolumeIcon {...props} /> },
    ]
  },
]);