name: Publish Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'    
        required: true
        default: '0.0.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@modclub-app'

      - name: Install dependencies
        run: yarn install

      - name: Update version in package.json
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Build
        run: yarn build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit updated package.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "chore: bump version to ${{ github.event.inputs.version }}"
          git push